const servicesTable = [{
    "id": 51, // key : value
    "service": "Tres-Zap",
    "trademark": "Skynoodle",
    "branches": 63,
    "country": "Indonesia",
    "status": false
  }, {
    "id": 41,
    "service": "Duobam",
    "trademark": "Jabbersphere",
    "branches": 88,
    "country": "Russia",
    "status": true
  }, {
    "id": 27,
    "service": "Y-find",
    "trademark": "Jamia",
    "branches": 12,
    "country": "Luxembourg",
    "status": false
  }, {
    "id": 74,
    "service": "Tin",
    "trademark": "Youopia",
    "branches": 12,
    "country": "Sweden",
    "status": false
  }, {
    "id": 59,
    "service": "Tampflex",
    "trademark": "Flashdog",
    "branches": 23,
    "country": "China",
    "status": false
  }, {
    "id": 93,
    "service": "Fintone",
    "trademark": "Youspan",
    "branches": 43,
    "country": "Indonesia",
    "status": false
  }, {
    "id": 47,
    "service": "Temp",
    "trademark": "Skipstorm",
    "branches": 24,
    "country": "Palestinian Territory",
    "status": true
  }, {
    "id": 26,
    "service": "Sonsing",
    "trademark": "Flashset",
    "branches": 42,
    "country": "China",
    "status": false
  }, {
    "id": 98,
    "service": "Biodex",
    "trademark": "Vinder",
    "branches": 97,
    "country": "Philippines",
    "status": true
  }, {
    "id": 17,
    "service": "Pannier",
    "trademark": "Topicblab",
    "branches": 86,
    "country": "China",
    "status": true
  }, {
    "id": 95,
    "service": "Overhold",
    "trademark": "Realcube",
    "branches": 15,
    "country": "Russia",
    "status": true
  }, {
    "id": 5,
    "service": "Fixflex",
    "trademark": "Twimbo",
    "branches": 52,
    "country": "Brazil",
    "status": true
  }, {
    "id": 62,
    "service": "Alpha",
    "trademark": "Realbuzz",
    "branches": 23,
    "country": "Czech Republic",
    "status": true
  }, {
    "id": 33,
    "service": "Y-Solowarm",
    "trademark": "Voonder",
    "branches": 19,
    "country": "Colombia",
    "status": false
  }, {
    "id": 66,
    "service": "Aerified",
    "trademark": "Blogspan",
    "branches": 75,
    "country": "Portugal",
    "status": true
  }, {
    "id": 62,
    "service": "Veribet",
    "trademark": "Mynte",
    "branches": 11,
    "country": "Bulgaria",
    "status": false
  }, {
    "id": 15,
    "service": "Fix San",
    "trademark": "Minyx",
    "branches": 12,
    "country": "Poland",
    "status": false
  }, {
    "id": 42,
    "service": "Sub-Ex",
    "trademark": "Devify",
    "branches": 8,
    "country": "United States",
    "status": true
  }, {
    "id": 21,
    "service": "Voyatouch",
    "trademark": "Twitterbeat",
    "branches": 80,
    "country": "Belarus",
    "status": true
  }, {
    "id": 33,
    "service": "Voltsillam",
    "trademark": "Skyba",
    "branches": 6,
    "country": "France",
    "status": false
  }, {
    "id": 25,
    "service": "Voyatouch",
    "trademark": "Wordpedia",
    "branches": 62,
    "country": "China",
    "status": false
  }, {
    "id": 22,
    "service": "Andalax",
    "trademark": "Kayveo",
    "branches": 35,
    "country": "China",
    "status": false
  }, {
    "id": 3,
    "service": "Cookley",
    "trademark": "Browsecat",
    "branches": 39,
    "country": "China",
    "status": true
  }, {
    "id": 48,
    "service": "Mat Lam Tam",
    "trademark": "Vitz",
    "branches": 69,
    "country": "Ukraine",
    "status": true
  }, {
    "id": 52,
    "service": "Greenlam",
    "trademark": "Demivee",
    "branches": 25,
    "country": "United States",
    "status": false
  }, {
    "id": 97,
    "service": "Konklux",
    "trademark": "Mymm",
    "branches": 46,
    "country": "Philippines",
    "status": false
  }, {
    "id": 41,
    "service": "Matsoft",
    "trademark": "Plajo",
    "branches": 12,
    "country": "Georgia",
    "status": false
  }, {
    "id": 26,
    "service": "Toughjoyfax",
    "trademark": "Meetz",
    "branches": 100,
    "country": "Poland",
    "status": true
  }, {
    "id": 85,
    "service": "Fixflex",
    "trademark": "Divanoodle",
    "branches": 34,
    "country": "China",
    "status": false
  }, {
    "id": 82,
    "service": "Konklab",
    "trademark": "Skimia",
    "branches": 48,
    "country": "Indonesia",
    "status": false
  }, {
    "id": 14,
    "service": "Holdlamis",
    "trademark": "Aimbu",
    "branches": 63,
    "country": "Japan",
    "status": true
  }, {
    "id": 81,
    "service": "Andalax",
    "trademark": "Yakitri",
    "branches": 89,
    "country": "Indonesia",
    "status": false
  }, {
    "id": 68,
    "service": "Tresom",
    "trademark": "Zooveo",
    "branches": 19,
    "country": "Indonesia",
    "status": false
  }, {
    "id": 13,
    "service": "Sub-Ex",
    "trademark": "Zoomlounge",
    "branches": 45,
    "country": "France",
    "status": false
  }, {
    "id": 10,
    "service": "Flowdesk",
    "trademark": "Devpoint",
    "branches": 57,
    "country": "Mexico",
    "status": false
  }, {
    "id": 4,
    "service": "Biodex",
    "trademark": "Topiclounge",
    "branches": 80,
    "country": "Indonesia",
    "status": false
  }, {
    "id": 90,
    "service": "Flexidy",
    "trademark": "Eidel",
    "branches": 14,
    "country": "Sweden",
    "status": true
  }, {
    "id": 60,
    "service": "Toughjoyfax",
    "trademark": "Wikizz",
    "branches": 26,
    "country": "China",
    "status": true
  }, {
    "id": 12,
    "service": "Fixflex",
    "trademark": "Miboo",
    "branches": 24,
    "country": "Thailand",
    "status": true
  }, {
    "id": 93,
    "service": "Y-find",
    "trademark": "Browsebug",
    "branches": 17,
    "country": "Canada",
    "status": true
  }, {
    "id": 37,
    "service": "Zaam-Dox",
    "trademark": "Jaxbean",
    "branches": 28,
    "country": "Serbia",
    "status": true
  }, {
    "id": 79,
    "service": "Flexidy",
    "trademark": "Oba",
    "branches": 61,
    "country": "Iran",
    "status": true
  }, {
    "id": 56,
    "service": "Sub-Ex",
    "trademark": "Mudo",
    "branches": 67,
    "country": "Bangladesh",
    "status": false
  }, {
    "id": 8,
    "service": "Quo Lux",
    "trademark": "Meevee",
    "branches": 99,
    "country": "China",
    "status": false
  }, {
    "id": 20,
    "service": "Vagram",
    "trademark": "Flashpoint",
    "branches": 67,
    "country": "Poland",
    "status": true
  }, {
    "id": 51,
    "service": "Subin",
    "trademark": "Dabjam",
    "branches": 72,
    "country": "Colombia",
    "status": true
  }, {
    "id": 69,
    "service": "Temp",
    "trademark": "Topiczoom",
    "branches": 6,
    "country": "Palestinian Territory",
    "status": true
  }, {
    "id": 57,
    "service": "Flowdesk",
    "trademark": "Flipopia",
    "branches": 28,
    "country": "Russia",
    "status": true
  }, {
    "id": 28,
    "service": "Tres-Zap",
    "trademark": "Kwinu",
    "branches": 15,
    "country": "Indonesia",
    "status": true
  }, {
    "id": 35,
    "service": "Wrapsafe",
    "trademark": "Roomm",
    "branches": 55,
    "country": "Indonesia",
    "status": false
  }, ]

  export default servicesTable;